spring:
  application:
    name: kafka-listener-springboot-demo

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: ${spring.application.name}
      enable-auto-commit: false
    listener:
      ack-mode: manual_immediate

test-event-topic-name: test-event

server:
  port: 8081